In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

#Importing requests
import requests

# importing regex
import re

In [4]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/apple-iphone-12-mini-black-64-gb/product-reviews/itm38b727191eb08?pid=MOBFWBYZXSEGBS6F&lid=LSTMOBFWBYZXSEGBS6FTONJ6W&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=350
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 350 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df1=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df1

     Number of ratings                                        Full Review
0                    5  Good phone at this price point\nCamera is by f...
1                    5  Awesome Purchase…\nFirstly, thank you Flipkart...
2                    5  Very nice product... i am fully satisfied than...
3                    5  Apple iPhone 12 mini is incredible, peaceful t...
4                    5  Switched from android.Truecaller not working f...
...                ...                                                ...
3460                 5                                         Loved it !
3461                 5                                       Just awesome
3462                 5  Nice product and great service by Flipkart, Sa...
3463                 5                                         Good phona
3464                 4  The phone is outstanding except battery perfor...

[3465 rows x 2 columns]

In [8]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/poco-x3-pro-steel-blue-128-gb/product-reviews/itm527548fcdf883?pid=MOBGFKNF6HFYZWPY&lid=LSTMOBGFKNF6HFYZWPYQIBQSW&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=200
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 200 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df2=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df2

     Number of ratings                                        Full Review
0                    5  After satisfactory reviews, I made my decision...
1                    5  💠 Very Good Phone....\n\n💠 One Of The Best Aft...
2                    5  Awesome phone, just loved it..... mind-blowing...
3                    4  Bought in first sale with exciting 😀 got the p...
4                    5  If you are looking for a performance based pho...
...                ...                                                ...
1486                 5                                          Satisfied
1487                 4                                               Good
1488                 4                                         Good item.
1489                 3                   Camera is worst remaining ok ok.
1490                 5                                       Nice product

[1491 rows x 2 columns]

In [11]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/product-reviews/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=200
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 200 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df3=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df3

     Number of ratings                                        Full Review
0                    5  The Best Phone for the Money\n\nThe iPhone 11 ...
1                    5  Really satisfied with the Product I received.....
2                    5  Great iPhone very snappy experience as apple k...
3                    5  Amazing phone with great cameras and better ba...
4                    5  Previously I was using one plus 3t it was a gr...
...                ...                                                ...
1995                 5                          My first I phone my dream
1996                 5                                I love it so much ✨
1997                 1                                              Worst
1998                 5                                          Excellent
1999                 5                                               Nice

[2000 rows x 2 columns]

In [12]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/oppo-f17-pro-matte-black-128-gb/product-reviews/itm4e2fc7ddc621c?pid=MOBFVYVXMYEUDPTY&lid=LSTMOBFVYVXMYEUDPTYHN1ECS&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=169
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 169 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df4=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df4

     Number of ratings                                        Full Review
0                    5  The things I like:\n\nPhone looks Premium.\nCa...
1                    4  Specially I like Display, Design and weight.. ...
2                    5  One of the best product in mid range smartphon...
3                    5  Mobile is excellent camera nice battery super ...
4                    3  I live in Sitapur Uttar Pradesh.\n👍👍👍👍👍👍\nWow ...
...                ...                                                ...
1685                 5  Camera not good...audio speaker not good....ot...
1686                 1  NOT UP TO MARK, YOU CAN GET SAMSUNG M31S INSTE...
1687                 5  Just Awesome mobile, very light weight and sli...
1688                 5               It's too light.......awwwsom product
1689                 5                                      Great Product

[1690 rows x 2 columns]

In [16]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/apple-iphone-xr-white-64-gb-includes-earpods-power-adapter/product-reviews/itmf9z7zhgzkmgm3?pid=MOBF9Z7ZUYC2EYQD&lid=LSTMOBF9Z7ZUYC2EYQDVYJTIC&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=400
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 400 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df5=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df5

     Number of ratings                                        Full Review
0                    5  It's so good with a medium size screen and muc...
1                    5  Awesome smart phone.... Loved it.\nBig display...
2                    5  This phone is Epic💕💕💕Just loved it!! Camera is...
3                    5  Writing this review after using iPhone XR for ...
4                    5  Very nice product with great features.... supe...
...                ...                                                ...
3975                 5                                        Good camera
3976                 4                                   Just love it too
3977                 3  I don't like price fluctuations for mobiles. P...
3978                 4                                           Nice one
3979                 5                                Value for money ❤️👍

[3980 rows x 2 columns]

In [17]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/samsung-galaxy-f12-sky-blue-64-gb/product-reviews/itm0319ce24f74aa?pid=MOBGFG79BVGDHGWV&lid=LSTMOBGFG79BVGDHGWVGF2CRI&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=500
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 500 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df6=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df6

     Number of ratings                                        Full Review
0                    4  Best Samsung phone in this price range.Good ba...
1                    5  This smartphone is very good in camera and bat...
2                    4  First I would like to thank you Flipkart for f...
3                    5  Pros:-\nBattery backup is simply awesome. I go...
4                    5  Best mobile for in this price range, Battery b...
...                ...                                                ...
4854                 3                                     Value of money
4855                 1                 Screen always get freezed and hang
4856                 5                                          Very nice
4857                 1  Many app and system settings not working prope...
4858                 5                                         Very happy

[4859 rows x 2 columns]

In [21]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/boat-rockerz-235v2-asap-charging-version-5-0-bluetooth-headset/product-reviews/itm22bd40cdad692?pid=ACCFZGAQJGYCYDCM&lid=LSTACCFZGAQJGYCYDCMGNWASG&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=150
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 150 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df7=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df7

     Number of ratings                                        Full Review
0                    3  Hi Seekers, I am writing this review after 2 w...
1                    5  I like It Boat HP Sound Quality is bestm best\...
2                    5  Wawo wawooo wawooooo..😍😍 I am so happy with th...
3                    5  Very Good Product.\nSound is very Clear and ba...
4                    5     Super sound and good looking I like that prize
...                ...                                                ...
1442                 1                                   My money waste 😭
1443                 5                                       Good product
1444                 3                                               Good
1445                 5  Same model before I used one year nice product...
1446                 1                 Worest one month using not working

[1447 rows x 2 columns]

In [24]:
driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(3)

url = "https://www.flipkart.com/boult-audio-airbass-combuds-bluetooth-headset/product-reviews/itm930fff9f49371?pid=ACCFVFRHCBSZFKVJ&lid=LSTACCFVFRHCBSZFKVJSADT2C&marketplace=FLIPKART"
driver.get(url)

time.sleep(2)

# Creating empty list
page_urls=[]
complete_review=[]
stars=[]
start=0
end=300
time.sleep(2)

#scrapping all product Url

for page in range(start,end):#for loop for scrapping 300 pages
    url=driver.find_elements_by_xpath("//a[@class='ge-49M _2Kfbh8']")
    for i in url:
        page_urls.append(i.get_attribute('href'))
    nxt_button=driver.find_elements_by_xpath("//a[@class='_1LKTO3']")
    try:
        driver.get(nxt_button[1].get_attribute('href'))     #getting the link from the list for next page
    except:
        driver.get(nxt_button[0].get_attribute('href'))
            

for i in page_urls:
    driver.get(i)
    #for scrapping the number of stars
    for j in driver.find_elements_by_xpath("//div[@class='col _2wzgFH K0kLPL']/div[1]/div[1]"):
        stars.append(j.text)
    #for scrapping the complete review
    for l in driver.find_elements_by_xpath("//div[@class='t-ZTKy']/div/div"):
        complete_review.append(l.text)
               
        
#Combining all the lists into a single dataframe
df8=pd.DataFrame({'Number of ratings': stars,
               'Full Review': complete_review})
df8

     Number of ratings                                        Full Review
0                    5  Best in this price. best design. sound, bass q...
1                    4  Review after a month used\n1) built & looks go...
2                    5  Superb sound and bass quality is awesome excel...
3                    4  Most beautiful product i get in cheaper price ...
4                    1  Don't buy...... Useless product... Touch not w...
...                ...                                                ...
2939                 3                                            Arrange
2940                 5                                    Great product 👍
2941                 1                         Mike not properly work 🙄🙄🙄
2942                 5                                    Nice product 😊😊
2943                 2   Calling quality was poor & disappointed with it.

[2944 rows x 2 columns]

In [25]:
Review_data = pd.concat([df1,df2,df2,df4,df5,df6,df7,df8])

In [27]:
Review_data.shape

(21367, 2)

In [29]:
Review_data.to_csv("Review_data.csv")

In [30]:
Review_data.head()

  Number of ratings                                        Full Review
0                 5  Good phone at this price point\nCamera is by f...
1                 5  Awesome Purchase…\nFirstly, thank you Flipkart...
2                 5  Very nice product... i am fully satisfied than...
3                 5  Apple iPhone 12 mini is incredible, peaceful t...
4                 5  Switched from android.Truecaller not working f...

In [31]:
import os

In [32]:
os.getcwd()

'C:\\Users\\lokes\\DataTrained practice'